### ISSUE TITLE
Would love to learn more about how to use this? Is it compatible with Inky Frame (drag and forget is exactly what I'm after)? Can it run with the battery pack?

### ISSUE THREAD

**Issue by petruut** [meoiswa/firebasewebgallery#1]

**Comment by meoiswa** [comment]
This is a Firebase Functions project intended to host images online for display on the the InkyFrame, it requires knowledge of Firebase to deploy your own function, store your files, and the webgallery.py script to be loaded on the InkyFrame.
It's a solution for "fire-and-forget deployment" of images to the inkyframe, not a "fire-and-forget solution", and is not intended for public use as-is
